import { LoginButton } from '@/components/LoginButton';
import { LogoutButton } from '@/components/LogoutButton';
import styles from '@/styles/Home.module.css';
import { useAuth0 } from '@auth0/auth0-react';
import { Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { user, isAuthenticated, isLoading, getAccessTokenSilently } = useAuth0();

  console.log(getAccessTokenSilently());

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isAuthenticated && (
          <>
            <p>Logged in!</p>
            <LogoutButton />
          </>
        )}
        {!isAuthenticated && !isLoading && <LoginButton />}
      </main>
    </>
  );
}
